name: Swift Format

on:
  push:
    # paths:
    #   - "mobile/ios/**/*.swift"
    branches:
      - main

jobs:
  swift_format:
    name: swift-format
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tap
        run: brew tap pointfreeco/formulae
      - name: Install
        run: brew install Formulae/swift-format@5.3
      - name: Format
        run: make format
        working-directory: "mobile/ios"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style(ios): run swift-format"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
